---
- name: Vérifier si vim est installé
  hosts: alpine
  tasks:
    - name: Vérifier si vim est installé
      command: "which vim"
      register: vim_installed
      ignore_errors: yes

    - name: Afficher le statut de vim
      debug:
        msg: "vim est {{ 'installé' if vim_installed.rc == 0 else 'non installé' }}"
